dirTypeFile = ["Images", "Videos", "Audios", "Documents", "Compressed", "Executable", "Code"]
formatFiles = {
    "jpg": "Images",
    "png": "Images",
    "gif": "Images",
    "mp4": "Videos",
    "mkv": "Videos",
    "avi": "Videos",
    "mp3": "Audios",
    "wav": "Audios",
    "flac": "Audios",
    "txt": "Documents",
    "doc": "Documents",
    "docx": "Documents",
    "pdf": "Documents",
    "zip": "Compressed",
    "rar": "Compressed",
    "7z": "Compressed",
    "exe": "Executable",
    "msi": "Executable",
    "deb": "Executable",
    "rpm": "Executable",
    "html": "Code",
    "css": "Code",
    "js": "Code",
    "py": "Code",
    "java": "Code",
    "c": "Code",
    "cpp": "Code",
    "cs": "Code",
    "go": "Code",
    "kt": "Code",
    "php": "Code",
    "rb": "Code",
    "swift": "Code",
    "xml": "Code",
    "json": "Code",
    "yaml": "Code",
    "yml": "Code",
    "csv": "Code",
    "sql": "Code",
    "bat": "Code",
    "cmd": "Code",
    "ps1": "Code",
}

PAHT = "/home/pool/Descargas"
